### ISSUE TITLE
Daemon pods keep failing

### ISSUE THREAD

**Issue by jbonnett92** [storageos/storageos.github.io#251]
Hi,
I am trying to install StorageOS on my Kubernetes cluster, Kubernetes is installed in CoreOS.
Looking at the logs the one line that stands out is: `panic: runtime error: slice bounds out of range`

```
time="2019-01-02T12:22:39Z" level=info msg="by using this product, you are agreeing to the terms of the StorageOS Ltd. End User Subscription Agreement (EUSA) found at: https://eusa.storageos.com" module=command
time="2019-01-02T12:22:39Z" level=info msg=starting address=********* hostname=clust1-worker-1 id=856a20dd-1e6f-aabf-a152-fa3c4f5dc5a5 join="*********,*********" module=command version="StorageOS 1.0.2 (13c3612), built: 2018-12-07T140018Z"
panic: runtime error: slice bounds out of range
 goroutine 1 [running]:
code.storageos.net/storageos/control/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).Region(0xc4200c4650, 0x0, 0xc420296760, 0xc4208e9080, 0xc4204bcc20)
	/go/src/code.storageos.net/storageos/control/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:122 +0xa3
code.storageos.net/storageos/control/integration/iaas/ec2.(*Provider).GetZone(0xc4202997e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x20002)
	/go/src/code.storageos.net/storageos/control/integration/iaas/ec2/provider.go:112 +0x59
code.storageos.net/storageos/control/controlplane.applyProviderMetadata(0xc4201df900, 0x1fc0600, 0xc4202997e0, 0x0, 0xc4204416b0)
	/go/src/code.storageos.net/storageos/control/controlplane/node.go:234 +0x1ea
code.storageos.net/storageos/control/controlplane.applyMetadata(0xc4201df900, 0x9, 0x1f94b90)
	/go/src/code.storageos.net/storageos/control/controlplane/node.go:229 +0x66
code.storageos.net/storageos/control/controlplane.writeNodeBootstrapConfig(0x1fc07c0, 0xc42037b620, 0xc420279900, 0xc42000e178, 0xc420440060)
	/go/src/code.storageos.net/storageos/control/controlplane/node.go:194 +0xd60
code.storageos.net/storageos/control/controlplane.Create(0xc420279900, 0xc4204d0fe0, 0xc42000e178, 0x1f97820, 0xc4200c4a38, 0x0, 0x1f8a7c8, 0x7)
	/go/src/code.storageos.net/storageos/control/controlplane/server.go:182 +0xb52
code.storageos.net/storageos/control/command/server.(*Command).Run(0xc4201968c0, 0xc4200ca010, 0x0, 0x0, 0xc4204d09c0)
	/go/src/code.storageos.net/storageos/control/command/server/command.go:122 +0x8f4
code.storageos.net/storageos/control/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201b0a00, 0xc4201b0a00, 0xc4204d0a00, 0x0)
	/go/src/code.storageos.net/storageos/control/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.realMain(0xc4200a6058)
	/go/src/code.storageos.net/storageos/control/main.go:38 +0x126
main.main()
	/go/src/code.storageos.net/storageos/control/main.go:26 +0x22
```

Any ideas what could be causing this?

Thanks,
Jamie

**Comment by jbonnett92** [comment]
@domodwyer My servers are not on AWS.

**Comment by domodwyer** [comment]
Hi @jbonnett92 

The above PR was fixing a broader issue with the AWS SDK (panicking when receiving an unexpected response to a "get region" EC2 metadata request) that should also resolve your ticket.

I believe this _only_ happens because your servers are not in AWS, as within AWS you would assume the SDK always receives a valid response. Do you happen to have a HTTP server listening on `169.254.169.254` in your environment?

Dom

**Comment by jbonnett92** [comment]
@domodwyer I was just confirming that I wasn't :)

**Comment by jbonnett92** [comment]
@domodwyer Could you update the helm chart for it too please? Unless it uses this repository as a resource?

**Comment by domodwyer** [comment]
Hey @jbonnett92 - we absolutely will!

I'll leave this ticket open until the release is out and the chart has been updated so you know when it's all sorted 👍 

Dom

**Comment by actionbuddha** [comment]
Hi @jbonnett92 , just to let you know we are preparing a release now and expect to release next Monday or Tuesday, at which point we'll update the Helm charts and documentation. I'll ping a final update when that's done.

**Comment by jbonnett92** [comment]
@actionbuddha Thank you

**Comment by jbonnett92** [comment]
@actionbuddha I noticed the recent merge, does that mean it is ready for me to use?

**Comment by actionbuddha** [comment]
Hi @jbonnett92 yes, 1.1.0 is now released - please do go ahead and try it. Can you confirm back here if it solves your issue plz?

**Comment by darkowlzz** [comment]
@jbonnett92 Hi, as per the logs, you're running `StorageOS 1.1.0`, that's from the helm chart 0.2.10 release.
The failure seems to be related to connectivity issue with the embedded key value store. Usually when you have IPs in the join token, one of those IPs should be your current node's IP address. You've redacted the starting address (advertise IP), but you've some IPs in the join token. Can you check if the advertise IP of this node is in one of the IPs in the join token? If not that could be the reason for kv store connection timeouts.
Also, I would recommend clearing `/var/lib/storageos` from all the nodes to ensure any old configurations are removed.

An alternative to avoid messing around with these IPs is to use the [cluster operator](https://github.com/storageos/charts/tree/master/stable/storageoscluster-operator), it will make the installation easier. You can follow the docs and try it out.
Since you need the latest version, please add the following in the cluster spec when you try it:
```
spec:
  ...
  images:
    nodeContainer: storageos/node:1.1.0
  ...
```
This will work with k8s 1.12 and below. Support for k8s 1.13 will be release soon.

**Comment by darkowlzz** [comment]
Private IPs should work fine.
And this would work in k8s 1.13 as well, but not if you are installing using CSI. The in-tree plugin (non-CSI - default) installation should work fine on k8s 1.13.

Here's an example of a setup, hope it helps. Let's say I've 3 nodes with internal IPs 10.1.10.165, 10.1.10.166 and 10.1.10.167.
If I run the installation right, the log would be something like:
```
starting address=10.1.10.167 hostname=test01 id=9341sdf2-2a25-734fbb6daaf2 join="10.1.10.165,10.1.10.166,10.1.10.167"
```
Can you verify that's what you get in the logs?

I'll check if there's anything else that could be causing this issue.

**Comment by darkowlzz** [comment]
@jbonnett92 can you also share the helm command with all the parameters you're running to install?

**Comment by jbonnett92** [comment]
@darkowlzz Yes and the only other thing installed is Calico CNI. That line was in the logs above although it shows the public IP's for some reason.

Here was the Helm command that I used:
`helm install storageos/storageos --name=storageos --version=0.2.10 --namespace=storageos --set cluster.join="10.8.96.3\,10.8.96.4\,10.8.96.5"`

**Comment by avestuk** [comment]
@jbonnett92 What size is your cluster? When @darkowlzz mentioned 3 nodes that was referring to 3 worker nodes. StorageOS will only work as a single node cluster or as a three, or more, node cluster. This is because we use etcd to maintain consensus and it's not possible to get a consensus with a two node cluster. 

My suggestion would be that you install StorageOS on three nodes, alternatively you can install StorageOS on a single node but this means you won't be able to use volume replicas, and therefore your volumes won't be highly available. 

If you have further questions I'm also available on our public slack channel storageos.slack.com

**Comment by jbonnett92** [comment]
@avestuk I have 1 master and 2 workers.

**Comment by avestuk** [comment]
@jbonnett92 then the only remaining option is to install StorageOS on a single node. A single node installation has some limitations but it'll work.

**Comment by actionbuddha** [comment]
Hi, closing this out because I believe the original issue was resolved. @jbonnett92 if you get any issues not related to this ticket, please do come and find us on our public Slack channel, or mail support@storageos.com. Thanks!
