### ISSUE TITLE
Not enough storage in Pool?

### ISSUE THREAD

**Issue by jbonnett92** [storageos/storageos.github.io#282]
Hi,
I am trying to make a PV claim and apparently I don't have enough storage when I do.
Any ideas what could be causing this?
<img width="566" alt="Screenshot 2019-03-27 at 03 55 54" src="https://user-images.githubusercontent.com/3740700/55049508-6ee4d700-5044-11e9-8d50-e25b4ffe30b1.png">
<img width="1084" alt="Screenshot 2019-03-27 at 03 56 16" src="https://user-images.githubusercontent.com/3740700/55049513-71dfc780-5044-11e9-8eff-4258d4df9383.png">
 
Although I can add two 40GB volumes
<img width="1104" alt="Screenshot 2019-03-27 at 04 18 59" src="https://user-images.githubusercontent.com/3740700/55050235-883b5280-5047-11e9-8837-b29eba94ceef.png">

**Comment by avestuk** [comment]
@jbonnett92 How much capacity does each node in your cluster have? In order to create a volume, the volume must be able to fit on a single node.

**Comment by jbonnett92** [comment]
@avestuk Ahh I didn't realise that

**Comment by jbonnett92** [comment]
I actually had to reinstall and now I can't get StorageOS to run on my cluster, any ideas? It's stuck in a loop of "Back-off restarting failed container" although if I click on the logs I just get 1 line that says pod initializing.

**Comment by avestuk** [comment]
@jbonnett92 You might want to delete /var/lib/storageos on each node before restarting. How many nodes do you have in your cluster? I can see that you have at least two, node0 and node1, if you are using embedded etcd then you have to use 1, or 3+ nodes. This is because etcd cannot get quorum if there are only two nodes.

I may be able to help you in a less asynchronous manner if you DM me on our [Public slack](https://slack.storageos.com/)
